Repository posomo/saltit-server, pull requests merged in 2023-05, with the labels that each got.

#37 [Fix] add restaurantSummary to restaurantId
  .github/workflows/ci-test.yml
  src/main/java/com/posomo/saltit/domain/restaurant/dto/RestaurantSummary.java
  src/main/java/com/posomo/saltit/respository/RestaurantRepository.java
  src/main/java/com/posomo/saltit/service/RestaurantService.java
Labels: fix

#36 [Feat] Github action을 통한 CI 스크립트 생성
  .github/workflows/ci-test.yml
Labels: feature, ci/cd

#40 Fix: CI 감지 폴더명 변경 및 Action이름 변경
  .github/workflows/ci-test.yml
Labels: bug, fix

#51 [Feat] FilterRequest에 Options 추가
  src/main/java/com/posomo/saltit/domain/restaurant/dto/RestaurantFilterRequest.java
  src/main/java/com/posomo/saltit/repository/RestaurantRepositoryImpl.java
  src/test/java/com/posomo/saltit/repository/RestaurantRepositoryImplTest.java
Labels: enhancement, fix

#54 fix: remove mkdir command
  .github/workflows/ci-test-dev.yml
  .github/workflows/ci-test-main.yml
  .github/workflows/deploy-test-server.yml
  .github/workflows/deploy.yml
Labels: ci/cd, fix

#61 feat: add get Region List API
  src/main/java/com/posomo/saltit/controller/RegionController.java
  src/main/java/com/posomo/saltit/controller/RegionControllerV1.java
  src/main/java/com/posomo/saltit/controller/RegionControllerV1Swagger.java
  src/main/java/com/posomo/saltit/domain/region/dto/RegionListResponseDto.java
  src/main/java/com/posomo/saltit/domain/region/entity/District.java
  src/main/java/com/posomo/saltit/domain/region/entity/Region.java
  src/main/java/com/posomo/saltit/repository/DistrictRepository.java
  src/main/java/com/posomo/saltit/repository/RegionRepository.java
  src/main/java/com/posomo/saltit/service/RegionService.java
  src/main/java/com/posomo/saltit/service/RegionServiceV1.java
Labels: feature
